spring:
  application:
  name: kiwee

  config:
    import:
      - classpath:application-database.yaml
      - classpath:application-oauth.yaml

  web:
    resources:
      add-mappings: false

server:
  port: 8080
  forward-headers-strategy: framework
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-exception: true

